// Authentication actions
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const UPDATE_USER = 'UPDATE_USER';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_IS_REVENUECAT_PREMIUM = 'SET_IS_REVENUECAT_PREMIUM';
export const SET_USER_NOTIFICATION_PREFERENCES =
  'SET_USER_NOTIFICATION_PREFERENCES';
