// homeData actions
export const API_REQUEST_HOME = 'API_REQUEST_HOME';
export const API_SUCCESS_HOME = 'API_SUCCESS_HOME';
export const API_LIST_END_HOME = 'API_LIST_END_HOME';
export const RESTORE_DEFAULT_HOME = 'RESTORE_DEFAULT_HOME';
export const RESTORE_DEFAULT_HOME_SINGLE_TAB =
  'RESTORE_DEFAULT_HOME_SINGLE_TAB';
export const UPDATE_HOME = 'UPDATE_HOME';
export const UPDATE_BETS = 'UPDATE_BETS';
export const BATCH_UPDATE_HOME = 'BATCH_UPDATE_HOME';
export const SAVE_CLOSED_APP_TIMESTAMP = 'SAVE_CLOSED_APP_TIMESTAMP';
export const SET_ALREADY_CONFIGURED_REVENUECAT =
  'SET_ALREADY_CONFIGURED_REVENUECAT';
