// Notification actions
export const API_REQUEST_NOTIFICATIONS = 'API_REQUEST_NOTIFICATIONS';
export const API_SUCCESS_NOTIFICATIONS = 'API_SUCCESS_NOTIFICATIONS';
export const API_LIST_END_NOTIFICATIONS = 'API_LIST_END_NOTIFICATIONS';
export const RESTORE_DEFAULT_NOTIFICATIONS = 'RESTORE_DEFAULT_NOTIFICATIONS';
export const REALTIME_UPDATE_NOTIFICATIONS = 'REALTIME_UPDATE_NOTIFICATIONS';
