// offersData actions
export const API_REQUEST_OFFERS_DATA = 'API_REQUEST_OFFERS_DATA';
export const API_SUCCESS_OFFERS_DATA = 'API_SUCCESS_OFFERS_DATA';
export const API_LIST_END_OFFERS_DATA = 'API_LIST_END_OFFERS_DATA';
export const RESTORE_DEFAULT_OFFERS_DATA = 'RESTORE_DEFAULT_OFFERS_DATA';
export const REALTIME_INSERT_OFFERS_DATA = 'REALTIME_INSERT_OFFERS_DATA';
export const REALTIME_UPDATE_OFFERS_DATA = 'REALTIME_UPDATE_OFFERS_DATA';
export const SAVE_CLOSED_APP_TIMESTAMP = 'SAVE_CLOSED_APP_TIMESTAMP';
